# Generated by Django 5.0.2 on 2024-04-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("major", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "Students",
            },
        ),
    ]
